services:
  postgres:
    image: postgres
    container_name: postgres-task-management
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: taskmanagement
    ports:
      - "5426:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: taskmanagement_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/taskmanagement
      NODE_ENV: development
    ports:
      - "5000:4000"
    volumes:
      - ./backend:/app  # Mount local files for live reload
      - /app/node_modules  # Prevent overwriting node_modules
    command: sh -c "npm run start:dev"

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: taskmanagement_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4300:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data:
    driver: local

